### PR TITLE
honourPact takes an optional name

### PR DESCRIPTION
**Pull request by mikefarah**
This allows users to provide contextualised names for test reporting if desired.

Thoughts?

### CODE REVIEW

**Comment by tarciosaraiva** [comment]
I like that. Just wondering if you could not use the consumer/provider name that is already in the context?

https://github.com/mikefarah/pact-js-mocha/blob/609e14b079a31bc6519a9ce94f7e5d2bd2fad40e/src/index.js#L89

**Comment by mikefarah** [comment]
The reason I'm adding is is that we have actually receive seperate PACT files from our consumer for the different interaction types. E.g. one pact file for 'query' interactions, another one for 'create'. They can, of course, be all included in one PACT but this way it's easier to diagnose issues from both ends, and run them individually when fixing an issue.

This fix would let us have nicer test reports, where we would be honouring multiple interaction types for a given consumer.

**Comment by tarciosaraiva** [comment]
I see, so it's the same provider / consumer but different Pact files. I don't have a problem with this change but I think this could be something that pact-node could help as it can take an array of files or a directory location.

Anyway, I will think trough a bit more but am merging your change 👍

**Comment by mikefarah** [comment]
sweet :)

pact-js-mocha takes an array of files too, but the test report then looks like

```
<consumer> has pact with <provider> honours interactions
<consumer> has pact with <provider> honours interactions
<consumer> has pact with <provider> honours interactions
<consumer> has pact with <provider> honours interactions
```

instead of something like

```
<consumer> has pact with <provider> honours query interactions
<consumer> has pact with <provider> honours create interactions
<consumer> has pact with <provider> honours blah interactions
```

**Comment by mikefarah** [comment]
Also is this going to be published to NPM? I can't use it otherwise...

**Comment by tarciosaraiva** [comment]
Yup. Probably later today, is that OK? After lunch I can do it.

**Comment by mikefarah** [comment]
Legend 👯

**Comment by tarciosaraiva** [comment]
Hey @mikefarah just thought I should let you know that I've released v1.0.2-alpha just now. Sorry for the delay :+1:

**Comment by mikefarah** [comment]
No worries already onto it, works a treat! Thanks for the fast response :)

**Pull request merged**
